#Created by robot_tests
#sli-min-template.yaml
apiVersion: project-468.com/v1
kind: Sli
metadata:
  name: test-sample-ws--gitlab-merge-success-rate--sli
  namespace: default
  labels:
    origin-workspace: test-sample-ws
    workspace: test-sample-ws
    origin-slx: test-sample-ws--gitlab-merge-success-rate
    slx: test-sample-ws--gitlab-merge-success-rate
spec:
  locations:
  - k3d-location
  description: SLI Crud Test Continuous Regression
  codeBundle:
    repoUrl: https://git.dev.project-468.com/468-test/test-codebundles
    pathToRobot: gitlab-merge/sli.robot
    ref: main
  requirements:
  - pip: requirements.txt
  intervalStrategy: intermezzo
  intervalSeconds: 360
  configProvided:
  - name: sli_foo
    value: sli_bar
