#Created by robot_tests
#runbook-cb-template.yaml
apiVersion: project-468.com/v1
kind: Runbook
metadata:
  name: test-sample-ws--sli-img-build-deploy--runbook
  namespace: default
  labels:
    origin-workspace: test-sample-ws
    workspace: test-sample-ws
    origin-slx: test-sample-ws--sli-img-build-deploy
    slx: test-sample-ws--sli-img-build-deploy
spec:
  location: k3d-location
  description: Runbook description
  requirements:
  - pip: requirements.txt
  codeBundle:
    repoUrl: https://git.dev.project-468.com/468-test/test-codebundles
    pathToRobot: sli-crud/runbook.robot
    ref: main
  intervalStrategy: intermezzo
  intervalSeconds: 360
  configProvided:
  - name: rb_foo
    value: rb_bar
