#Created by robot_tests
#sli-min-template.yaml
apiVersion: project-468.com/v1
kind: Sli
metadata:
  name: test-sample-ws--gke-zonal-availability--sli
  namespace: default
  labels:
    origin-workspace: test-sample-ws
    workspace: test-sample-ws
    origin-slx: test-sample-ws--gke-zonal-availability
    slx: test-sample-ws--gke-zonal-availability
spec:
  locations:
  - k3d-location
  description: GCP/GKE calls to add to our nodepool should succeed 99.99% of the time
  codeBundle:
    repoUrl: https://git.dev.project-468.com/468-test/test-codebundles
    pathToRobot: gke-nodes-avail/sli.robot
    ref: main
  requirements:
  - pip: requirements.txt
  intervalStrategy: intermezzo
  intervalSeconds: 360
  configProvided:
  - name: sli_foo
    value: sli_bar
