#Created by robot_tests
#runbook-cb-template.yaml
apiVersion: project-468.com/v1
kind: Runbook
metadata:
  name: test-sample-ws--corestate-cluster-health--runbook
  namespace: default
  labels:
    origin-workspace: test-sample-ws
    workspace: test-sample-ws
    origin-slx: test-sample-ws--corestate-cluster-health
    slx: test-sample-ws--corestate-cluster-health
spec:
  location: k3d-location
  description: The K8s health score of the cluster should be >98%, 99% of the time
  requirements:
  - pip: requirements.txt
  codeBundle:
    repoUrl: https://git.dev.project-468.com/468-test/test-codebundles
    pathToRobot: kube-health-score/runbook.robot
    ref: main
  intervalStrategy: intermezzo
  intervalSeconds: 360
  configProvided:
  - name: rb_foo
    value: rb_bar
